### ISSUE TITLE
sign in fails

### ISSUE THREAD

**Issue by trvrcr** [myTselection/bibliotheek_be#11]
When inserting username and password the integration fails.
is it possible to hard code them in the configuration.yaml file?

**Comment by myTselection** [comment]
I didn't try via configuration.yaml, but it might work as some code for it exists.
is the login working with your credentials via bibliotheek.be > aanmelden? 
Will test again integration setup in coming days.

**Comment by myTselection** [comment]
I was able to reproduce it, but root cause not found yet. Will try to fix asap.

**Comment by myTselection** [comment]
fixed by skipping some validation step, will open a separate ticket to further check the input validation
