### ISSUE TITLE
2 accounts on one Home assistance give issue

### ISSUE THREAD

**Issue by trvrcr** [myTselection/bibliotheek_be#16]
When adding 2 accounts to home assistant there is only one warning created. 
In the logs you get the following error:

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:540
Integration: Sensor (documentation, issues)
First occurred: 17:42:59 (1 occurrences)
Last logged: 17:42:59

Platform bibliotheek_be does not generate unique IDs. ID Bibliotheek.be warning already exists - ignoring sensor.bibliotheek_be_warning

**Comment by myTselection** [comment]
You can [add multiple library cards](https://bibliotheek.be/mijn-bibliotheek/lidmaatschappen) within the bibliotheek.be account. No need to add multiple accounts.
I know, it may not cover all use cases, but else I'll have to add a username in every sensor...
