### ISSUE TITLE
Barcode and picture

### ISSUE THREAD

**Issue by s4nd3er** [myTselection/bibliotheek_be#22]
I see in the 'detail for users  , no barcode or pictures, do i change something on the code for this?
![2024-01-11 22_51_19-Dwains Dashboard – Home Assistant](https://github.com/myTselection/bibliotheek_be/assets/154844720/e00acdeb-cac8-4bb9-aa09-b0f46c28b829)

**Comment by myTselection** [comment]
Did you keep the markdown code as set in Readme? 
I'd expect exact copy paste of the markdown script can be used for your own markdown element.
It needs the placeholders to get URL out of sensor attributes, I don't see any placeholders in the markdown source shown in this screenshot...

**Comment by s4nd3er** [comment]
Yes, i just copy/paste it now...

![image](https://github.com/myTselection/bibliotheek_be/assets/154844720/821f97a4-1506-41b7-b5a3-234d4868ea9f)

**Comment by michaelvandorpe** [comment]
Make sure to paste it in the code editor rather than in the visual editor of the markdown card. That's what I did wrong at first...

**Comment by s4nd3er** [comment]
> Make sure to paste it in the code editor rather than in the visual editor of the markdown card. That's what I did wrong at first...

indeed, that was the problem, thanks!
