### ISSUE TITLE
Separate standalone mijn.bibliotheek API library

### ISSUE THREAD

**Issue by wvanhed** [myTselection/bibliotheek_be#25]
Hi,

Just want to let you know that a few months ago, I published a standalone mijn.bibliotheek.be Python API library at https://github.com/wvanhed/mijnbib
It's a big cleanup of code I've been using for a long time, extended with some functionality from your HA implementation.

Not sure if you want to depend on an external library, but could be of your interest anyway.

**Comment by myTselection** [comment]
Thx for sharing! looks nice :)
For now, I don't see major needs to integrate it, while it would require a lot of rewrite and would result in external dependency which I'd prefer not to have if not needed.

**Comment by wvanhed** [comment]
Yes, sure. Completely understandable
