### ISSUE TITLE
Sensors unavailable

### ISSUE THREAD

**Issue by BartVanBouwel** [myTselection/bibliotheek_be#26]
Since a couple of days I have the problem that all the sensors are unavailable.
After reloading the biliotheek integration, I get the following error in he log:

![image](https://github.com/myTselection/bibliotheek_be/assets/96834093/08a99fda-b236-4909-b5bd-874c1121a2d8)

Any Idea?
If I login on the website there isn't any problem.

Thanks for the help!

Best regards
Bart

**Comment by myTselection** [comment]
I have seen the same. Will try follow up in the coming days...

**Comment by myTselection** [comment]
fixed as of R1.6.10

**Comment by BartVanBouwel** [comment]
Your fix works! Thanks!!
