### ISSUE TITLE
Problem with single quote

### ISSUE THREAD

**Issue by BartVanBouwel** [myTselection/bibliotheek_be#30]
Hi,

I love this integration. It works super!

But I have one issue: when a book has a title with a single quote (ascii 39) in it. I can't split the list to use it on my page. Is it possible to replace a single quote with a curved single quote (ascii 0146)?
Probably this will also be the case with the author...

from:
![image](https://github.com/user-attachments/assets/135294fe-1094-4a72-a77d-bed9a683304a)

to:
![image](https://github.com/user-attachments/assets/a23fa15b-3a00-4961-b540-6574d52b668c)

Many Thanks!

**Comment by myTselection** [comment]
sure, this would be possible. But it's not fully clear to me why this would be needed. If you'd show this on a page, it would be easy to replace in the variable usage too:` {{ book.title.replace("'","´")}}`

**Comment by BartVanBouwel** [comment]
I have this code that split up the list. Because of the single quotes in the list, the split get's messed up of the extra single quote.
Maybe I am doing something wrong. But I could find it. It works perfect when there isn't a single quote in the title.

Thanks

My Code:
`<H3>Aantal boeken:
  {{state_attr('sensor.bibliotheek_be_xxxxx',
  'num_loans')}}</h3>  

  {% set lijst = state_attr('sensor.bibliotheek_be_xxxx',
  'loandetails')|string|replace("'",'"')|from_json %} 

  <table cellpadding="5"><tr>     {% for item in lijst %}
    {#Add row every x items#}
    {% if loop.index == 7 %}</tr><tr>
    {% endif %}
    
    <td><b>{{ lijst[item].title}}</b><br>
    {{ lijst[item].author}}<br>
    <img src="{{ lijst[item].image_src}}" height="200px"><br>
    {{ lijst[item].days_remaining}} dagen<br>
    {{ lijst[item].library}}</td>
  {% endfor %}  </tr> </table>`


Result should be:
![image](https://github.com/user-attachments/assets/46acdf50-ee2e-4fd0-a0c1-0b1da0dec273)

**Comment by myTselection** [comment]
To get a list you can use:

‘’‘
{% set all_books = state_attr(library,'loandetails')| list |sort(attribute="days_remaining", reverse=False) %}
{% for book in all_books %}
  {{book.title}}
{% endfor %}
‘’‘

See example markdown code: https://github.com/myTselection/bibliotheek_be?tab=readme-ov-file#markdown-example-for-details-of-all-libraries

**Comment by BartVanBouwel** [comment]
I found the problem thanks to your example.
I need to use this:

{% set books = state_attr(entity,'loandetails').values() |sort(attribute="days_remaining", reverse=False) %}  

 

With the .values() in stead of transforming it to a list. That doesn’t work for me.
The books with a single quote are no problem anymore.

Thanks for the help!

 

Best regards

Bart
