### ISSUE TITLE
Log warning about deprecated alis

### ISSUE THREAD

**Issue by TomVgw** [myTselection/bibliotheek_be#35]
I received the following message within the logs:

Logger: homeassistant.core
Source: helpers/deprecation.py:222
First occurred: 20:55:44 (1 occurrences)
Last logged: 20:55:44
Config was used from bibliotheek_be, this is a deprecated alias which will be removed in HA Core 2025.11. Use homeassistant.core_config.Config instead, please report it to the author of the 'bibliotheek_be' custom integration

I am using version 1.7.4 of bibliotheek.be

HA information:
- Core 2024.11.2
- Supervisor 2024.11.2
- Operating System 13.2
- Frontend 20241106.2

**Comment by myTselection** [comment]
fixed in R1.7.5
